/**
 * Created by anton on 31/07/2017.
 */

app.config(['$routeProvider', function ($routeProvider) {
    $routeProvider
        // Home
        .when("/", {
            templateUrl: "home.html", controller: "HomeController"})
        // Paginas
        .when("/paesabobora", {
            templateUrl: "content/paesabobora.html",
            controller: "PaesAboboraController"})
		.when("/barrinha", {
            templateUrl: "content/barrinha.html",
		    controller: "BarrinhaController"})
        .when("/chefs", {
                templateUrl: "content/chefs.html",
                controller: "ChefsController"})
		.when("/boloamendoim", {
            templateUrl: "content/boloamendoim.html",
            controller: "BoloAmendoimController"})
		.when("/cookies", {
            templateUrl: "content/cookies.html",
            controller: "CookiesController"})
		.when("/paocastanha", {
            templateUrl: "content/paocastanha.html",
            controller: "PaoCastanhaController"})
		.when("/soufle", {
            templateUrl: "content/soufle.html",
            controller: "SoufleController"})
		.when("/bolobrig", {
            templateUrl: "content/bolobrig.html",
            controller: "BoloBrigController"})
		.when("/risoto", {
            templateUrl: "content/risoto.html",
            controller: "RisotoController"})
		.when("/bolocenoura", {
            templateUrl: "content/bolocenoura.html",
            controller: "BoloCenouraController"})
		.when("/rosquinhas", {
            templateUrl: "content/rosquinhas.html",
            controller: "RosquinhasController"})
		.when("/paodequeijo", {
            templateUrl: "content/paodequeijo.html",
            controller: "PaodeQueijoController"})
		.when("/hamburguer", {
            templateUrl: "content/hamburguer.html",
            controller: "HamburguerController"})
		.when("/brigadeiro", {
            templateUrl: "content/brigadeiro.html",
            controller: "BrigadeiroController"})
		.when("/crepioca", {
            templateUrl: "content/crepioca.html",
            controller: "CrepiocaController"})
		.when("/muffin", {
            templateUrl: "content/muffin.html",
            controller: "MuffinController"})
		.when("/sorvete", {
            templateUrl: "content/sorvete.html",
            controller: "SorveteController"})
		.when("/tortafolhada", {
            templateUrl: "content/tortafolhada.html",
            controller: "TortaFolhadaController"})
		.when("/semlactose", {
            templateUrl: "content/semlactose.html",
            controller: "SemLactoseController"})
		.when("/semgluten", {
            templateUrl: "content/semgluten.html",
            controller: "SemGlutenController"})	
		.when("/vegetarianos", {
            templateUrl: "content/vegetarianos.html",
            controller: "VegetarianosController"})
		.when("/veganos", {
            templateUrl: "content/veganos.html",
            controller: "VeganosController"})
		.when("/sobre", {
            templateUrl: "content/sobre.html",
            controller: "SobreController"})
		.when("/receitas", {
            templateUrl: "content/receitas.html",
            controller: "ReceitasController"})
		.when("/tortaricota", {
            templateUrl: "content/tortaricota.html",
            controller: "TortaRicotaController"})
		.when("/contato", {
            templateUrl: "content/contato.html",
            controller: "ContatoController"})
        .when("/chefs", {
                templateUrl: "content/chefs.html",
                controller: "ChefsController"})
		.when("/diabeticos", {
            templateUrl: "content/diabeticos.html",
            controller: "DiabeticosController"})
		.when("/fitness", {
            templateUrl: "content/fitness.html",
            controller: "FitnessController"})
		.when("/contato", {
            templateUrl: "content/contato.html",
            controller: "ContatoController"})
        .otherwise({redirectTo: "/index"});
}]);
